name: GitHub Deployment Tracker

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to create deployment for'
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  create-deployment:
    name: Create GitHub Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 100  

      - name: Generate Deployment Summary
        id: deployment-info
        run: |
          BRANCH=$(echo "${GITHUB_REF#refs/heads/}")
          echo "Branch: $BRANCH"

          JIRA_KEYS=$(git log -n 3 --pretty=format:"%s" | grep -Eo "[A-Z]+-[0-9]+" | sort -u | paste -sd "," -)
          echo "JIRA Keys: $JIRA_KEYS"

          SHORT_DESC="Branch: $BRANCH | JIRA: $JIRA_KEYS"
          echo "desc=$SHORT_DESC" >> $GITHUB_OUTPUT

      - name: Create Deployment in GitHub
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.token }}
          env: ${{ inputs.environment }}
          desc: ${{ steps.deployment-info.outputs.desc }}
          ref: ${{ github.sha }}

      - name: Mark Deployment as Successful
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.token }}
          env: ${{ inputs.environment }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
