name: Update Sandbox branch
on:
  workflow_call:

jobs:
  merge-branch:
    name: update Sandbox branch/env
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GH_PAT_TOKEN }}

      - name: Git configuration
        run: |
          git config --local user.email "itops@firstclose.com"
          git config --local user.name "ItOps-FC"

      - name: Sandbox sync with main
        run: |
          git fetch origin
          git checkout sandbox
          git reset --hard origin/main
          git push origin sandbox --force
