name: Scan code for vulnerabilities

on:
  workflow_call:
    inputs:
      env_name:
        required: false
        type: string
      # ----- snyk config
      continue_on_error:
        required: false
        type: boolean
        default: true
        description: "Snyk continue on error property value"
      debug_mode:
        required: false
        type: boolean
        default: false
        description: "Enable debug logs in Snyk CLI output"
    secrets:
      SNYK_TOKEN:
        required: true
        description: "Snyk API token for auth"

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env_name }}
    steps:
      - uses: actions/checkout@v3
      - uses: snyk/actions/setup@master

      - name: Snyk Code Scan
        shell: bash
        continue-on-error: ${{ inputs.continue_on_error }}
        run: snyk code test ${{ inputs.debug_mode == true && '--debug' || '' }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
