name: Scan docker images for Vulnerabilities
on:
  workflow_call:
    inputs:
      env_name:
        required: false
        type: string
      dockerfile_path:
        required: false
        type: string
        description: "Location of the Dockerfile"
      docker_ctx:
        required: false
        type: string
        default: "."
        description: "Docker context to build"
      # ----- snyk config
      continue_on_error:
        required: false
        type: boolean
        default: true
        description: "Snyk continue on error property value"
      debug_mode:
        required: false
        type: boolean
        default: false
        description: "Enable debug logs in Snyk CLI output"
      monitor:
        required: false
        type: boolean
        default: false
        description: "Enable Snyk monitor after the scan (send it to snyk dashboard)"
    secrets:
      SNYK_TOKEN:
        required: true
        description: "Snyk API token for auth"

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env_name }}
    steps:
      - uses: docker/setup-buildx-action@v3

      - name: Generate Dynamic Image Tag
        id: generate_tag
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S) # YYYYMMDDHHMMSS
          IMAGE_TAG="app-to-scan-${TIMESTAMP}"
          echo "Generated Image Tag: $IMAGE_TAG"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.docker_ctx }}
          push: false
          tags: ${{ steps.generate_tag.outputs.IMAGE_TAG }}
          load: true

      - name: snyk docker scan
        uses: snyk/actions/docker@master
        continue-on-error: ${{ inputs.continue_on_error }}
        with:
          image: ${{ steps.generate_tag.outputs.IMAGE_TAG }}
          command: ${{ inputs.monitor == true && 'monitor' || 'test' }}
          args: ${{ inputs.dockerfile_path && format('--file={0}', inputs.dockerfile_path) || '' }} ${{ inputs.debug_mode == true && '--debug' || '' }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
