name: Scan docker images for Vulnerabilities
on:
  workflow_call:
    inputs:
      dockerfile_path:
        required: false
        type: string
        description: "Location of the Dockerfile"
      docker_image:
        required: false
        type: string
        description: "Docker image to scan"
      # ----- snyk config
      continue_on_error:
        required: false
        type: boolean
        default: true
        description: "Snyk continue on error property value"
      debug_mode:
        required: false
        type: boolean
        default: false
        description: "Enable debug logs in Snyk CLI output"
      monitor:
        required: false
        type: boolean
        default: false
        description: "Enable Snyk monitor after the scan (send it to snyk dashboard)"

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - name: snyk docker scan
        uses: snyk/actions/docker@master
        continue-on-error: ${{ inputs.continue_on_error }}
        with:
          image: ${{ inputs.docker_image || '' }}
          command: ${{ inputs.monitor == true && 'monitor' || 'test' }}
          args: ${{ inputs.dockerfile_path && format('--file={0}', inputs.dockerfile_path) || '' }} ${{ inputs.debug_mode == true && '--debug' || '' }}
        env:
          SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
